### ISSUE TITLE
Feat: Generate department code

### ISSUE THREAD

**Issue by longdratech** [uranussolutions/minhdu-libs#1]
example package: https://github.com/moment/moment

Tạo chức năng generate mã bộ phận
1. Nếu bộ phận có 1 từ gồm 3 ký tự. ví dụ Kho -> KHO
2. Nếu bộ phận có 1 từ gồm 2 ký tự. ví dụ Ga -> GA1
3. Nếu bộ phận có 2 từ . ví dụ Nhân sự -> NSU
4. Nếu bộ phân có 3 từ. Quản lý tổng -> QLT
Xem thêm trong design
![Screen Shot 2021-04-15 at 10.28.06.png](https://images.zenhubusercontent.com/5ecdc959678feb098b7cfdf7/fbbfeafb-a96b-4bea-bff2-9b0cc4e45037)

**Comment by vokhanggg** [comment]
Update: generate code follow department
-------------------------------------------------------
Input: department name (maximum: 3 words)
Output: department code
-------------------------------------------------------
Example:
Department Name: Human Resources
=> Department Code: HRE
! Department Code Error: NONE
[generateCode.min.js.zip](https://github.com/longth97/minhdu-libs/files/6319652/generateCode.min.js.zip)
